### ISSUE TITLE
us12 - Fin de session - Lien vers bande annonce

### ISSUE THREAD

**Issue by Rincevent42** [WildCodeSchool/lyon-js-03-20-p2-g4#14]
#### Story

En tant qu'utilisateur, je voudrais accéder à la bande annonce des films matchés conjointement afin de m'aider à choisir le film à regarder

#### Critères (et considération spécifiques)

L'écran de fin de session propose de cliquer le(s) film(s) matché(s) pour être redirigés vers leur bande annonce

#### (Scénarios de tests)

- Je termine une session avec match(s)
- L'écran affiche le(s) film(s) matché(s)
- Un symbole m'indique où cliquer pour avoir accès à la bande annonce

#### (Tâches)

- Générer dynamiquement l'URL
- Ajouter un événement au clic qui renvoi à l'URL

**Comment by AmelieChevalier** [comment]
Plus d'actualité, géré par l'us15.
