### ISSUE TITLE
us7 - Sélection des films - Boutons validation et élimination

### ISSUE THREAD

**Issue by AmelieChevalier** [WildCodeSchool/lyon-js-03-20-p2-g4#21]
### Story

En tant qu'utilisateur, je veux pouvoir cliquer sur un bouton afin de sélectionner les films que j'ai envie de regarder ou éliminer les films que je ne veux pas regarder

### Critères et considérations spécifiques

- Quand le film est affiché, deux boutons (croix rouge et check vert) permettent de selectionner ou non le film
- Après ma sélection, le film suivant dans la liste remplace le précédent

### Scénarios de test

- Je vois un titre de film
- Je peux cliquer sur un bouton correspondant à mon choix
- Le film suivant s'affiche à l'écran

### Tâches

- Ajouter les boutons de choix
- Prévoir le défilement de la liste après le clique sur un bouton
- Prévoir le push dans un array en cas de validation du film
- CSS
- Responsive

**Comment by Gudira2** [comment]
Bonjour! Merci pour un article très intéressant. Je l'ai lu avec beaucoup d'intérêt et de curiosité. Je veux aussi dire que je regarde des films gratuitement, ici [https://frenchstream.tube/](https://frenchstream.tube/) Streaming video
